/**
 * composables/useChangelog.js
 * Single source of truth for the application changelog.
 * Used by both HelpModal (full history) and WelcomeModal (latest release only).
 * `text` and `date` are { en, es }; `localized` still accepts a plain string.
 */

/** Text of a changelog field in the given language, falling back to English. */
export function localized(value, lang = 'en') {
  if (value == null || typeof value === 'string') return value
  return value[lang] || value.en || ''
}

export const CHANGELOG_VERSION = '1.17.0'

export const CHANGELOG = [
  {
    version: 'Unreleased',
    date: { en: 'In development', es: 'En desarrollo' },
    items: [
      { type: 'new', text: { en: 'Multicloud log intelligence (#92) — opt in per GCP Cloud Run/Function or Vercel project; estimate up to five Cloud Logging requests or two Vercel API requests per sync before enabling, then analyze sanitized events from the encrypted local cache; Vercel runtime logs are distinct from build logs and bounded reads respect Retry-After', es: 'Inteligencia de logs multicloud (#92) — activación optativa por recurso Cloud Run/Cloud Function de GCP o proyecto Vercel; estima hasta cinco solicitudes de Cloud Logging o dos de Vercel por sync antes de activar y analiza eventos sanitizados desde la caché local cifrada; los runtime logs de Vercel son distintos de los logs de build y las lecturas acotadas respetan Retry-After' } },
      { type: 'better', text: { en: 'KUApps product Advisor v2 — shows APM/log error-budget burn, filters recent technical findings through verified scopes and application registry membership, and links high technical risk with budget burn; DORA stays explicitly unavailable until correlated release and commit history exists', es: 'Advisor de producto v2 de KUApps — muestra el consumo del presupuesto de error de APM/logs, filtra hallazgos técnicos recientes por scopes verificados y membresía del registry, y relaciona riesgos técnicos altos con el consumo; DORA queda explícitamente no disponible hasta contar con historial correlacionado de releases y commits' } },
      { type: 'new', text: { en: 'Provider Advisor coverage (#95) — AWS IAM, SQS, SNS, DynamoDB and CloudFront checks; S3 uses a separate confirmed scan with a bucket/request cost estimate and a 15-minute cache; Kubernetes adds RBAC, Pod Security Admission and widely mounted Secret checks; Vercel reviews preview protection and credential-like variable names without exposing values; deprecated-runtime catalogs carry a review date and six-month freshness test; capped collections are marked partial', es: 'Cobertura del Advisor por proveedor (#95) — chequeos de IAM, SQS, SNS, DynamoDB y CloudFront; S3 usa un scan separado con confirmación, estimación de costo por buckets/solicitudes y caché de 15 minutos; Kubernetes suma RBAC, Pod Security Admission y Secrets montados por muchos pods; Vercel revisa la protección Preview y nombres de variables que parecen credenciales sin exponer valores; los catálogos de runtimes deprecados incluyen fecha de revisión y un test de vigencia de seis meses; las colecciones acotadas se marcan como parciales' } },
      { type: 'better', text: { en: 'Observability log history — chart cached error and warning rates from 30-day buckets with per-series freshness and explicit gaps; share the application error-rate objective with log events and compare recurring signature growth against the previous 24 hours', es: 'Historial de logs en Observability — grafica tasas cacheadas de errores y warnings desde buckets de 30 días con frescura y brechas explícitas; comparte el objetivo de tasa de error con eventos de logs y compara el crecimiento de firmas recurrentes con las 24 horas anteriores' } },
      { type: 'better', text: { en: 'Compact KUApps log coverage — show resource counts first and keep uncached or unavailable-scope resource names in a bounded expandable list', es: 'Cobertura compacta de logs en KUApps — mostrar primero el conteo y dejar los nombres sin caché o sin scope disponible en una lista desplegable acotada' } },
      { type: 'better', text: { en: 'KUApps product Advisor — analyzes sanitized cached log aggregates per AWS/Kubernetes resource and its verified account/region or cluster/namespace scope; separates high error rates, recurring failures, uncached groups and unavailable access without raw logs or cloud calls', es: 'Advisor de producto de KUApps — analiza agregados sanitizados de logs cacheados por recurso AWS/Kubernetes y su scope verificado de cuenta/región o clúster/namespace; distingue tasas altas, fallas recurrentes, grupos sin caché y falta de acceso, sin logs crudos ni llamadas a la nube' } },
      { type: 'better', text: { en: 'Background tasks panel — live elapsed runtime, provider labels, and 30-day AWS cost by activity where metered; costs are not attributed to individual runs, other providers remain untracked, and transitions respect reduced-motion settings', es: 'Panel de tareas en segundo plano — tiempo transcurrido en vivo, proveedor y costo AWS de 30 días por actividad cuando se mide; el costo no se atribuye a ejecuciones individuales, otros proveedores quedan sin medir y las transiciones respetan movimiento reducido' } },
    ],
  },
  {
    version: '1.17.0',
    date: { en: 'September 2026', es: 'Septiembre 2026' },
    items: [
      { type: 'new', text: { en: 'Desktop background mode — closing the window hides KUA in the system tray without stopping the backend; restore, explicitly quit, configure the close behavior, and reopen the existing instance when Linux tray support is unavailable', es: 'Modo de escritorio en segundo plano — al cerrar la ventana KUA se oculta en la bandeja sin detener el backend; se puede recuperar, salir explícitamente, configurar el cierre y reabrir la instancia existente si Linux no ofrece bandeja' } },
      { type: 'new', text: { en: 'Background tasks panel — inspect active, scheduled and recent work from the shared header, see process-wide CPU/memory without attributing it to tasks, and use only API-announced controls; polling stops when closed and refreshes on restore', es: 'Panel de tareas en segundo plano — consulta el trabajo activo, programado y reciente desde el header compartido, ve CPU/memoria global sin atribuirla a tareas y usa solo controles anunciados por la API; las consultas se detienen al cerrar y se actualizan al restaurar' } },
      { type: 'new', text: { en: 'Architecture Canvas — opt-in rollout history for Kubernetes Deployments and security findings from AWS, GCP and Kubernetes, loaded on demand and projected only onto matching resource identities', es: 'Architecture Canvas — historial optativo de rollouts para Deployments de Kubernetes y hallazgos de seguridad de AWS, GCP y Kubernetes, cargados bajo demanda y proyectados solo sobre identidades de recursos coincidentes' } },
      { type: 'new', text: { en: 'AWS Overview: active account, identity, regions and resource counts per service, this month\'s cost with forecast (Cost Explorer, cached 12h), activity KPIs and services with resources outside KUA', es: 'Resumen de AWS: cuenta activa, identidad, regiones y recursos por servicio, costo del mes con proyección (Cost Explorer, en caché 12 h), KPIs de actividad y servicios con recursos fuera de KUA' } },
      { type: 'new', text: { en: 'AWS SQS, SNS and SES: queues, topics and email identities with 24h activity, health status with reasons, Lambda consumers, subscription filters and DLQs, delivery status logs, suppression list and configuration set metrics', es: 'SQS, SNS y SES en AWS: colas, tópicos e identidades de correo con actividad de 24 h, estado de salud con motivos, consumidores Lambda, filtros y DLQ de suscripciones, logs de entrega, lista de supresión y métricas por configuration set' } },
      { type: 'new', text: { en: 'Local metric history: metrics already read are kept, so details only request what is missing and 24h/7d/30d charts reuse them, cutting billed CloudWatch reads', es: 'Historial local de métricas: lo ya leído se guarda, así los detalles solo piden lo que falta y los gráficos de 24 h / 7 d / 30 d lo reutilizan, bajando las lecturas cobradas de CloudWatch' } },
      { type: 'new', text: { en: 'CloudWatch dashboards drawn inside KUA: metric, Logs Insights (with a scan estimate before running), alarm and text widgets on their original layout', es: 'Dashboards de CloudWatch dibujados dentro de KUA: widgets de métricas, Logs Insights (con estimación de lectura antes de correr), alarmas y texto en su diseño original' } },
      { type: 'new', text: { en: 'Lambda and Step Functions tables show 24h invocations/executions and whether each resource writes logs', es: 'Las tablas de Lambda y Step Functions muestran invocaciones/ejecuciones de 24 h y si cada recurso escribe logs' } },
      { type: 'new', text: { en: 'AWS access requests: permission errors name the denied IAM action and suggest the policy for the whole screen', es: 'Solicitudes de acceso en AWS: los errores de permisos indican la acción IAM denegada y sugieren la policy de toda la pantalla' } },
      { type: 'new', text: { en: 'Kubernetes Overview with pods by status, problems and Prometheus trends; tables remember filters, sort and quick-filter chips', es: 'Resumen de Kubernetes con pods por estado, problemas y tendencias de Prometheus; las tablas recuerdan filtros, orden y chips de filtro rápido' } },
      { type: 'new', text: { en: 'Options: cache and refresh per provider with the cost of each automatic read, plus local storage usage (databases, tables, files)', es: 'Opciones: caché y actualización por proveedor con el costo de cada lectura automática, más el uso de almacenamiento local (bases, tablas, archivos)' } },
      { type: 'new', text: { en: 'Console saved connections: save a session with a name and reopen it with one click; sessions can be renamed', es: 'Conexiones guardadas en la Consola: guarda una sesión con nombre y vuelve a abrirla con un clic; las sesiones se pueden renombrar' } },
      { type: 'new', text: { en: 'GCP Cloud Run, VM and Cloud SQL details, labels, state history and VM SSH; Vercel project selector; EKS and VPC Info panels; Route 53 search and DNS tests', es: 'GCP: detalles de Cloud Run, VMs y Cloud SQL, labels, historial de estado y SSH a VMs; selector de proyecto en Vercel; paneles Info de EKS y VPC; búsqueda y pruebas DNS en Route 53' } },
      { type: 'better', text: { en: 'English is now the base language, with the whole interface translated to English and Spanish', es: 'El inglés pasa a ser el idioma base, con toda la interfaz traducida a inglés y español' } },
      { type: 'fix', text: { en: 'Auto-refresh no longer repeats billed CloudWatch reads every 5 s (about USD 4/h with the Lambda tab open); also fixes dashboard log widgets with ARN sources and stale Vercel data after switching projects', es: 'La auto-actualización ya no repite lecturas cobradas de CloudWatch cada 5 s (unos USD 4/h con la pestaña de Lambda abierta); también corrige widgets de logs con ARN y datos viejos de Vercel al cambiar de proyecto' } },
    ],
  },
  {
    version: '1.16.0',
    date: { en: 'September 2026', es: 'Septiembre 2026' },
    items: [
      { type: 'new',    text: { en: 'Console Sessions — one-click "Open in Console" actions on EC2 rows (⚡ SSM), GCP Cloud Run logs and Vercel deployments; closes the Console epic (#36-43)', es: 'Console Sessions — acciones "Open in Console" de un clic en filas de EC2 (⚡ SSM), Logs de GCP Cloud Run y deployments de Vercel; cierra el épico de Consola (#36-43)' } },
      { type: 'fix',    text: { en: 'Every Console session opened from Architecture, Observability or the new contextual actions now records its real environment and application id instead of "environment: default"', es: 'Toda sesión de Consola abierta desde Architecture, Observability o las nuevas acciones contextuales ahora registra su environment y application id reales en vez de "environment: default"' } },
      { type: 'new',    text: { en: 'Console Sessions — GCP and Vercel join the Console: Cloud Run and Vercel deployment logs as read-only sessions, without a shell', es: 'Console Sessions — GCP y Vercel se suman a la Consola: logs de Cloud Run y de deployments de Vercel como sesiones de solo lectura, sin shell' } },
      { type: 'better', text: { en: 'GCP Cloud Shell is now explicitly marked as unavailable in the launcher, with the reason shown, since it cannot start from a service account credential', es: 'GCP Cloud Shell queda marcado explícitamente como no disponible en el lanzador, con el motivo visible, ya que no puede iniciarse desde una credencial de service account' } },
      { type: 'new',    text: { en: 'AWS SSM Session Manager — Console sessions without SSH keys; requires session-manager-plugin and explicit confirmation before connecting', es: 'AWS SSM Session Manager — sesiones desde la Consola sin llaves SSH, requiere session-manager-plugin instalado y confirmación explícita antes de conectar' } },
      { type: 'new',    text: { en: 'Console — tabs, order, active tab and wrap/height preferences survive a reload; restored sessions always come back disconnected and need an explicit Reconnect', es: 'Console — pestañas, orden, pestaña activa y preferencias de wrap/altura sobreviven a una recarga; las sesiones restauradas vuelven siempre desconectadas y requieren Reconectar explícito' } },
      { type: 'new',    text: { en: 'Console — command history shared and persisted per exact target, capped at 200 commands per target and 50 targets, with per-tab and global "Clear history" actions', es: 'Console — historial de comandos compartido y persistido por destino exacto, acotado a 200 comandos por destino y 50 destinos, con acciones de "Borrar historial" por pestaña y global' } },
      { type: 'better', text: { en: 'EC2 SSH joins the same shared Console registry as the local Terminal and Kubernetes logs/exec, with unified session states (connected/error/done/reconnecting/stopped)', es: 'EC2 SSH converge en el mismo registro compartido de Consola que Terminal local y Kubernetes logs/exec, con estados de sesión unificados (connected/error/done/reconnecting/stopped)' } },
      { type: 'fix',    text: { en: 'Removed the standalone local Terminal view, no longer needed after moving to the shared Console registry', es: 'Se eliminó la vista standalone de Terminal local, ya innecesaria tras la convergencia al registro compartido de Consola' } },
      { type: 'new',    text: { en: 'Global Console — a button in each module\'s header opens a single workspace with every active session and a launcher for the local Terminal and Kubernetes logs/exec', es: 'Console global — un botón en el header de cada módulo abre un workspace único con todas las sesiones activas y un lanzador para Terminal local y Kubernetes logs/exec' } },
      { type: 'new',    text: { en: 'Architecture Canvas — optional Kubernetes Events overlay on the affected nodes, with inline "View metrics here" / "View logs here" actions', es: 'Architecture Canvas — overlay opcional de Eventos de Kubernetes sobre los nodos afectados, con acciones inline "Ver métricas aquí" / "Ver logs aquí"' } },
      { type: 'better', text: { en: 'Console — context check before connecting; EC2 SSH/RDP use an Env Manager credential profile instead of passwords or key paths', es: 'Console — validación de contexto antes de conectar; EC2 SSH/RDP usan un perfil de credenciales del Env Manager en vez de contraseñas o rutas de llave' } },
    ],
  },
  {
    version: '1.15.0',
    date: { en: 'September 2026', es: 'Septiembre 2026' },
    items: [
      { type: 'new',    text: { en: 'Architecture Foundation — KUApps brings architecture and observability into an application-centered workspace, with shared resources and AWS, Kubernetes, GCP and Vercel discovery', es: 'Architecture Foundation — KUApps integra arquitectura y observabilidad en un espacio centrado en aplicaciones, con recursos compartidos y discovery AWS, Kubernetes, GCP y Vercel' } },
      { type: 'better', text: { en: 'Canvas — smart layouts with more room when overlays are on, and ordering by relationships inside provider/resource sections', es: 'Canvas — layouts inteligentes con más espacio al activar overlays y orden por relaciones dentro de secciones de proveedor/recurso' } },
      { type: 'new',    text: { en: 'Architecture Canvas — PDF export of the full diagram (nothing cut off) and download of the visible graph as a Mermaid file', es: 'Canvas Architecture — exportación a PDF del diagrama completo (sin recortes) y descarga del grafo visible como archivo Mermaid' } },
      { type: 'new',    text: { en: 'Architecture — new per-profile workspace to create application architecture projects, initially focused on AWS', es: 'Architecture — nuevo espacio por perfil para crear proyectos de arquitectura de aplicaciones orientados inicialmente a AWS' } },
      { type: 'new',    text: { en: 'Graph model — scopes, sources, nodes, relationships, groups, evidence and layout with a provider-independent contract', es: 'Modelo de grafo — ámbitos, fuentes, nodos, relaciones, grupos, evidencia y layout con contrato independiente del proveedor' } },
      { type: 'new',    text: { en: 'Local snapshots — private SQLite database with optimistic revisions, immutable history and per-profile isolation', es: 'Snapshots locales — base SQLite privada con revisiones optimistas, historial inmutable y aislamiento por perfil' } },
      { type: 'better', text: { en: 'Architecture workspace — project creation, graph summary and snapshot history from the main navigation', es: 'Workspace Architecture — creación de proyectos, resumen del grafo e historial de snapshots desde la navegación principal' } },
      { type: 'new',    text: { en: 'Operations and history — typed graph changes with optimistic revision, cascading cleanup and a semantic log per profile', es: 'Operaciones e historial — cambios tipados del grafo con revisión optimista, limpieza en cascada y registro semántico por perfil' } },
      { type: 'better', text: { en: 'Compare and restore — diff against snapshots and transactional recovery that keeps the history in a new immutable revision', es: 'Comparación y restauración — diff contra snapshots y recuperación transaccional que conserva el historial en una nueva revisión inmutable' } },
      { type: 'new',    text: { en: 'Interactive Canvas — create, connect, move, edit and delete components manually with Vue Flow, with the layout saved', es: 'Canvas interactivo — creación, conexión, movimiento, edición y eliminación manual de componentes con Vue Flow y persistencia del layout' } },
      { type: 'new',    text: { en: 'AWS discovery — read-only CloudFormation and ECS preview with explicit selection and atomic import of resources and inferred relationships', es: 'Discovery AWS — preview read-only de CloudFormation y ECS con selección explícita e importación atómica de recursos y relaciones inferidas' } },
      { type: 'new',    text: { en: 'Automatic relationships — classification by confidence threshold with visible evidence and distinct states for automatic and suggested relationships', es: 'Relaciones automáticas — clasificación por umbral de confianza con evidencia visible y estados diferenciados para relaciones automáticas y sugeridas' } },
      { type: 'better', text: { en: 'Human review — actions to accept or reject inferred relationships, keeping the decision and the history across new discovery runs', es: 'Revisión humana — acciones para aceptar o rechazar relaciones inferidas, preservando la decisión y el historial frente a nuevos discovery' } },
      { type: 'new',    text: { en: 'AWS semantics — triggers, invokes and runs-on relationships for EventBridge, Step Functions, ECS and SQS-to-Lambda event source mappings', es: 'Semántica AWS — relaciones triggers, invokes y runs on para EventBridge, Step Functions, ECS y event source mappings SQS a Lambda' } },
      { type: 'new',    text: { en: 'AWS regional inventory — direct discovery of Lambda, EventBridge and Step Functions, with CloudFormation as optional evidence', es: 'Inventario regional AWS — discovery directo de Lambda, EventBridge y Step Functions, con CloudFormation como evidencia opcional' } },
      { type: 'new',    text: { en: 'Identified applications — grouping of resources connected by AWS evidence, explicit selection and a warning when the 500-resource limit is reached', es: 'Aplicaciones identificadas — agrupación de recursos conectados por evidencia AWS, selección explícita y aviso al alcanzar el límite de 500 recursos' } },
      { type: 'fix',    text: { en: 'Drawing applications — direct action from discovery, safe reuse of the preview and a readable adaptive layout for large graphs', es: 'Dibujo de aplicaciones — acción directa desde discovery, reutilización segura del preview y layout adaptativo legible para grafos grandes' } },
      { type: 'new',    text: { en: 'APL diagram per event — configurable order by sequence, name, bus, service flow or longest route, also applied to branches', es: 'Diagrama APL por evento — orden configurable por secuencia, nombre, bus, flujo de servicios o ruta más larga, aplicado también a las ramas' } },
      { type: 'better', text: { en: 'Architecture setup — guided onboarding from CloudFormation to resource selection and diagram review, with optional regional inventory', es: 'Configuración Architecture — onboarding guiado desde CloudFormation a selección de recursos y revisión del diagrama, con inventario regional opcional' } },
      { type: 'new',    text: { en: 'Step Functions diagrams — access from Routes or the Canvas to each workflow\'s internal, configurable ASL diagram', es: 'Diagramas Step Functions — acceso desde Routes o Canvas al diagrama ASL interno configurable de cada workflow' } },
      { type: 'better', text: { en: 'Application inventory — regional event source mappings to complete SQS-to-Lambda relationships, and visible makeup of each candidate', es: 'Inventario aplicativo — event source mappings regionales para completar relaciones SQS a Lambda y composición visible de cada candidato' } },
      { type: 'new',    text: { en: 'Full CloudFormation — explicit import of every resource in the selected stacks, including isolated resources and new AWS services', es: 'CloudFormation completo — importación explícita de todos los recursos de los stacks seleccionados, incluidos recursos aislados y nuevos servicios AWS' } },
      { type: 'better', text: { en: 'CloudFormation relationships — dedicated semantics for S3 notifications, IAM roles and policies, Lambda permissions and governed resources', es: 'Relaciones CloudFormation — semántica dedicada para notificaciones S3, roles y policies IAM, permisos Lambda y recursos gobernados' } },
      { type: 'better', text: { en: 'Causal Canvas — saved horizontal or vertical order, fewer crossings, readable zoom, optional labels and AWS icons per service', es: 'Canvas causal — orden horizontal o vertical persistido, reducción de cruces, zoom legible, etiquetas opcionales e iconos AWS por servicio' } },
      { type: 'new',    text: { en: 'API Gateway routes — method and path shown, direct reference to the existing Lambda and navigation between components from the inspector', es: 'Rutas API Gateway — método y path visibles, referencia directa a la Lambda existente y navegación entre componentes desde el inspector' } },
      { type: 'better', text: { en: 'Canvas focus — selection centered with a readable zoom and automatic dimming of unrelated nodes and relationships', es: 'Foco del Canvas — selección centrada con zoom legible y atenuación automática de nodos y relaciones no vinculados' } },
      { type: 'fix',    text: { en: 'Canvas selection — clicking the background removes any leftover dimming and restores the full diagram', es: 'Selección del Canvas — al pulsar el fondo se elimina toda atenuación residual y se restaura la visibilidad completa del diagrama' } },
      { type: 'new',    text: { en: 'Order by type — sections with counters, deterministic grid, saved positions and faint straight connectors for large topologies', es: 'Orden por tipo — secciones con contador, rejilla determinista, posiciones persistidas y conectores rectos tenues para topologías grandes' } },
      { type: 'better', text: { en: 'Cost and privacy — Architecture discovery counts toward the per-profile AWS budget, without storing or exposing CloudFormation templates', es: 'Coste y privacidad — discovery Architecture integrado al presupuesto AWS por perfil, sin persistir ni exponer plantillas CloudFormation' } },
      { type: 'fix',    text: { en: 'Idempotent rediscovery — reconciles historical AWS identities without duplicating nodes, keeping manual decisions, groups and positions', es: 'Rediscovery idempotente — reconciliación de identidades AWS históricas sin duplicar nodos, conservando decisiones manuales, grupos y posiciones' } },
      { type: 'better', text: { en: 'Persistent view — Canvas mode and direction, relationship labels and snapshot comparison survive a reload', es: 'Vista persistente — modo y dirección del Canvas, etiquetas de relaciones y comparación de snapshots sobreviven a la recarga' } },
      { type: 'better', text: { en: 'Architecture phase 3 — acceptance criteria documented and closure validated with the backend/frontend suites and production builds', es: 'Architecture fase 3 — criterios de aceptación documentados y cierre validado con las suites backend/frontend y builds de producción' } },
      { type: 'new',    text: { en: 'Kubernetes adapter — read-only topology preview for workloads, pods, Services and Ingress with a stable UID identity per context and namespace', es: 'Adaptador Kubernetes — preview de topología solo lectura para workloads, pods, Services e Ingress con identidad UID estable por contexto y namespace' } },
      { type: 'better', text: { en: 'Kubernetes preview — explicit EKS cluster selection before loading workloads, with visible states for cluster listing and resource reads', es: 'Preview Kubernetes — selección explícita del cluster EKS antes de cargar workloads, con estados visibles para listado de clusters y lectura de recursos' } },
      { type: 'better', text: { en: 'Observability setup — Kubernetes is chosen as an explicit scope: light cluster loading and detection aimed only at the chosen EKS', es: 'Configuración Observability — Kubernetes se selecciona como ámbito explícito: carga ligera de clusters y detección dirigida solo al EKS elegido' } },
      { type: 'better', text: { en: 'Observability by capability — KPIs, charts, analysis and traces only appear when the application\'s confirmed resources support them', es: 'Observability por capacidad — KPIs, gráficas, análisis y trazas aparecen solo cuando los recursos confirmados de la aplicación los soportan' } },
      { type: 'new',    text: { en: 'Kubernetes logs from Observability — direct access to streaming of the configured Pods and workloads, resolving their Pods in the linked context', es: 'Logs Kubernetes desde Observability — acceso directo al streaming de Pods y workloads configurados, resolviendo sus Pods en el contexto asociado' } },
      { type: 'fix',    text: { en: 'Kubernetes usage — Pod availability and restarts no longer look incomplete when metrics.k8s.io is missing; it says that only CPU and memory are unavailable', es: 'Uso Kubernetes — la disponibilidad y reinicios de Pods ya no aparecen incompletos cuando falta metrics.k8s.io; se indica que solo CPU y memoria no están disponibles' } },
      { type: 'better', text: { en: 'Kubernetes usage — automatic fallback to the cluster\'s Prometheus for CPU and memory when Metrics Server is unavailable', es: 'Uso Kubernetes — fallback automático a Prometheus del cluster para CPU y memoria cuando Metrics Server no está disponible' } },
      { type: 'better', text: { en: 'Automatic Kubernetes preview — applications with configured workloads refresh their topology only in their assigned contexts and reuse the result when opened', es: 'Preview Kubernetes automático — las aplicaciones con workloads configurados actualizan su topología solo en los contextos asignados y reutilizan el resultado al abrirlo' } },
      { type: 'better', text: { en: 'Architecture from Observability — creating a view draws the application\'s confirmed resources and dependencies, not an empty graph', es: 'Architecture desde Observability — al crear una vista se dibujan los recursos y dependencias confirmados de la aplicación, no un grafo vacío' } },
      { type: 'new',    text: { en: 'Multicloud Architecture — a single menu to add resources: AWS and Kubernetes available, with GCP and Vercel adapters prepared as next steps', es: 'Architecture multicloud — menú único para agregar recursos: AWS y Kubernetes disponibles, con adaptadores GCP y Vercel preparados como próximos pasos' } },
      { type: 'new',    text: { en: 'Kubernetes Architecture — context selection, preview with health and relationships, and explicit import of confirmed resources in one revision', es: 'Architecture Kubernetes — selección de contexto, preview con salud y relaciones, e importación explícita de recursos confirmados en una revisión' } },
      { type: 'new',    text: { en: 'Architecture manual resources — add an EC2 or another AWS, Kubernetes, GCP or Vercel component with an explicit native identity, scope and location', es: 'Recursos manuales Architecture — agregar EC2 u otro componente AWS, Kubernetes, GCP o Vercel con identidad nativa, ámbito y ubicación explícitos' } },
      { type: 'better', text: { en: 'Kubernetes diagram — cluster and resource icons, Ingress/Service routes and declared dependencies on the ConfigMaps, Secrets and PVCs used by workloads', es: 'Diagrama Kubernetes — iconografía de cluster y recursos, rutas Ingress/Service y dependencias declaradas a ConfigMaps, Secrets y PVCs usados por workloads' } },
      { type: 'better', text: { en: 'Kubernetes discovery — namespace filter and selection grouped by type to decide which workloads, networking, configuration and storage go into the diagram', es: 'Discovery Kubernetes — filtro por namespace y selección agrupada por tipo para decidir qué workloads, red, configuración y almacenamiento entran al diagrama' } },
      { type: 'new',    text: { en: 'Application routes — APL for events/workflows and Kubernetes microservice routes from Ingress to Service, Pods and declared dependencies', es: 'Application routes — APL para eventos/workflows y rutas de microservicios Kubernetes desde Ingress a Service, Pods y dependencias declaradas' } },
      { type: 'better', text: { en: 'Kubernetes evidence — relationships from selectors and Ingress, workload/pod health, Warning events and per-context capabilities that degrade gracefully', es: 'Evidencia Kubernetes — relaciones por selectores e Ingress, salud de workload/pod, eventos Warning y capacidades degradables por contexto' } },
      { type: 'new',    text: { en: 'Shared KUA registry — provider-neutral resources, memberships and relationships with a stable identity and separate source lineage', es: 'Registro KUA compartido — recursos, membresías y relaciones neutrales al proveedor con identidad estable y linaje de fuentes separado' } },
      { type: 'better', text: { en: 'APM + Architecture correlation — explicit reconciliation that identifies shared resources and relationships without moving metrics, cursors or traces', es: 'Correlación APM + Architecture — conciliación explícita que identifica recursos y relaciones comunes sin mover métricas, cursores ni trazas' } },
      { type: 'new',    text: { en: 'KUA Application — reversible link between Observability and Architecture per profile, creating or choosing a diagram without migrating telemetry or resources', es: 'KUA Application — enlace reversible entre Observability y Architecture por perfil, con creación o selección de diagrama sin migrar telemetría ni recursos' } },
      { type: 'better', text: { en: 'Unified navigation — resource coverage, duplicate identity warnings and direct access from an application to its linked Architecture diagram', es: 'Navegación unificada — cobertura de recursos, avisos de identidad duplicada y acceso directo desde una aplicación al diagrama Architecture enlazado' } },
      { type: 'new',    text: { en: 'Authoritative CloudFormation sync — atomic apply with optimistic revision, stack metadata and preservation of identities and reviewed decisions', es: 'Sync CloudFormation autoritativo — aplicación atómica con revisión optimista, metadatos de stacks y conservación de identidades y decisiones revisadas' } },
      { type: 'better', text: { en: 'Sync review — concrete resources per category, an explicit stale cycle and actions to restore or delete missing resources', es: 'Revisión de sincronización — recursos concretos por categoría, ciclo stale explícito y acciones para restaurar o eliminar recursos ausentes' } },
      { type: 'better', text: { en: 'AWS discovery — visible status while loading stacks or analyzing resources and relationships, even during slow queries', es: 'Discovery AWS — estado visible al cargar stacks o analizar recursos y relaciones, incluso durante consultas demoradas' } },
      { type: 'new',    text: { en: 'Architecture projects — explicit, cascading deletion of the local graph, snapshots and revision history', es: 'Proyectos Architecture — eliminación explícita y en cascada del grafo local, snapshots e historial de revisiones' } },
      { type: 'fix',    text: { en: 'AFEX rediscovery — real validation of three stacks without node growth; new relationships are added as updated evidence', es: 'Rediscovery AFEX — validación real de tres stacks sin crecimiento de nodos; nuevas relaciones se incorporan como evidencia actualizada' } },
      { type: 'fix',    text: { en: 'Lambda layers — AWS::Lambda::LayerVersion is shown as a layer with its real name, never as a function with a numeric version', es: 'Capas Lambda — AWS::Lambda::LayerVersion se muestra como capa con su nombre real, nunca como función con una versión numérica' } },
      { type: 'better', text: { en: 'API Gateway to Lambda — permissions merged as route evidence, and a new inspector with routes, permissions and CloudFormation metadata', es: 'API Gateway a Lambda — permisos consolidados como evidencia de ruta y nuevo inspector con rutas, permisos y metadatos CloudFormation' } },
      { type: 'better', text: { en: 'Persistent Architecture context — the active application, project, provider and profile survive a window reload', es: 'Contexto Architecture persistente — la aplicación, proyecto, proveedor y perfil activos sobreviven a la recarga de la ventana' } },
      { type: 'fix',    text: { en: 'Architecture profile — an application with its own profile (local Kubernetes, GCP, Vercel) is no longer overwritten by the global AWS profile', es: 'Perfil Architecture — una aplicación con perfil propio (Kubernetes local, GCP, Vercel) ya no se sobreescribe con el perfil AWS global' } },
      { type: 'new',    text: { en: 'Navigation from the Canvas — logs, YAML/metrics and their own Pods for Kubernetes workloads; logs and an AWS view filtered by name for Lambda, EC2, EventBridge and Step Functions', es: 'Navegación desde el Canvas — logs, YAML/métricas y Pods propios para workloads Kubernetes; logs y vista AWS filtrada por nombre para Lambda, EC2, EventBridge y Step Functions' } },
      { type: 'new',    text: { en: 'Canvas health overlay — optional per-node badge with degraded/healthy status (Kubernetes) or a stale resource without recent discovery', es: 'Overlay de salud del Canvas — insignia opcional por nodo con estado degradado/saludable (Kubernetes) o recurso obsoleto sin discovery reciente' } },
      { type: 'new',    text: { en: 'Resources view — shared registry per KUA Application with provider, scope, the sources that confirm it and single-source divergences', es: 'Vista Resources — registro compartido por KUA Application con proveedor, scope, fuentes que lo confirman y divergencias de fuente única' } },
      { type: 'fix',    text: { en: 'Duplicate Kubernetes resources — Architecture and Observability now resolve the same identity (context/namespace/kind/name) instead of treating the app\'s provider and the workload\'s provider as different things', es: 'Recursos Kubernetes duplicados — Architecture y Observability ya resuelven la misma identidad (contexto/namespace/kind/nombre) en lugar de tratar el proveedor de la app y el del workload como cosas distintas' } },
      { type: 'fix',    text: { en: 'Registry reconciliation — an Architecture action no longer creates up to two extra graph revisions; projecting APM resources and stamping correlation ids are merged into one', es: 'Reconciliación del registro — una acción de Architecture ya no genera hasta dos revisiones adicionales de grafo; la proyección de recursos APM y el sellado de ids de correlación se fusionan en una sola' } },
      { type: 'new',    text: { en: 'Sync diagnostics — last successful sync, last error and divergent resources/relationships shown in Observability, with one-click retry', es: 'Diagnóstico de sincronización — última sincronización exitosa, último error y recursos/relaciones divergentes visibles en Observability, con reintento de un clic' } },
      { type: 'better', text: { en: 'Routes filters — provider, context and namespace can now be set from Routes too, not only from the Canvas', es: 'Filtros de Routes — proveedor, contexto y namespace ahora se controlan también desde Routes, no solo desde el Canvas' } },
      { type: 'new',    text: { en: 'Relationship suggestions from logs — deterministic, sanitized extraction of internal DNS references from the already open stream, added as reviewable suggested relationships', es: 'Sugerencias de relaciones desde logs — extracción determinista y sanitizada de referencias DNS internas en el stream ya abierto, agregadas como relaciones sugeridas revisables' } },
      { type: 'new',    text: { en: 'Lambda environment variable discovery — SQS queues, DynamoDB tables, S3 buckets and SNS topics referenced by ARN or URL are suggested as relationships, without downloading or running the function\'s code', es: 'Discovery de variables de entorno Lambda — colas SQS, tablas DynamoDB, buckets S3 y tópicos SNS referenciados por ARN o URL se sugieren como relaciones, sin descargar ni ejecutar el código de la función' } },
      { type: 'new',    text: { en: 'Discovery from the IAM role and static code — the execution role\'s capabilities as a weak suggestion, and opt-in static analysis of the Lambda package (never executed) to find literal references', es: 'Discovery por rol IAM y código estático — capacidades del rol de ejecución como sugerencia débil, y análisis estático opt-in del paquete de la Lambda (nunca se ejecuta) para detectar referencias literales' } },
      { type: 'better', text: { en: 'Generalized discovery — any recognizable ARN is suggested as a resource even when the service has no dedicated support; added SNS fan-out discovery and a warning for unresolved cross-stack dependencies', es: 'Discovery generalizado — cualquier ARN reconocible se sugiere como recurso aunque el servicio no tenga soporte dedicado, se agregó descubrimiento de fan-out SNS y aviso de dependencias cross-stack no resueltas' } },
      { type: 'fix',    text: { en: 'Retry sync — resources of types Observability does not support yet (S3, SNS, DynamoDB, generic) are no longer counted as divergent, since they could never be confirmed from both sides', es: 'Retry sync — recursos de tipos que Observability no soporta aún (S3, SNS, DynamoDB, genéricos) ya no se cuentan como divergentes, ya que nunca podrían confirmarse desde ambos lados' } },
      { type: 'new',    text: { en: 'Shared S3, SNS and DynamoDB — they now correlate as a single resource between Architecture and Observability instead of being duplicated or left only on the Architecture side', es: 'S3, SNS y DynamoDB compartidos — ahora correlacionan como un solo recurso entre Architecture y Observability en vez de duplicarse o quedar solo del lado de Architecture' } },
      { type: 'fix',    text: { en: 'Kubernetes identity — a workload\'s Kind is no longer inferred from an unreliable API field; it is known up front from the queried endpoint, avoiding duplicate resources and nodes', es: 'Identidad Kubernetes — el Kind de un workload ya no se infiere de un campo poco confiable de la API; se conoce de antemano según el endpoint consultado, evitando recursos y nodos duplicados' } },
      { type: 'new',    text: { en: 'Resources already added — the AWS and Kubernetes discovery panels now mark resources that are already in the project instead of showing them like new ones', es: 'Recursos ya agregados — los paneles de discovery de AWS y Kubernetes ahora marcan los recursos que ya están en el proyecto, en vez de mostrarlos igual que los nuevos' } },
      { type: 'better', text: { en: 'Kubernetes type — Kubernetes resources in Observability now show their specific type (Deployment, Pod, Service...) instead of a generic "Kubernetes", in both Resources and Topology', es: 'Tipo Kubernetes — los recursos Kubernetes en Observability ahora muestran su tipo específico (Deployment, Pod, Service...) en vez de "Kubernetes" genérico, tanto en Resources como en Topology' } },
      { type: 'new',    text: { en: 'Per-item divergence — divergent resources and relationships are now marked one by one besides the total count, with the same rule ready for future GCP/Vercel resources', es: 'Divergencia por elemento — recursos y relaciones divergentes ahora se marcan individualmente además del conteo agregado, con la misma regla lista para futuros recursos de GCP/Vercel' } },
      { type: 'new',    text: { en: 'Kubernetes relationships from metadata — Deployments now relate to other resources from references in their environment variables (internal DNS or service name), as Lambda already does on AWS', es: 'Relaciones Kubernetes por metadata — los Deployments ahora se relacionan con otros recursos según referencias en sus variables de entorno (DNS interno o nombre de servicio), igual que ya pasa con Lambda en AWS' } },
      { type: 'fix',    text: { en: 'Kubernetes CPU/memory via Prometheus — the Prometheus fallback when there is no Metrics Server now works on real clusters; before, the query path got corrupted and never arrived', es: 'CPU/memoria de Kubernetes vía Prometheus — el respaldo a Prometheus cuando no hay Metrics Server ahora funciona en clústeres reales; antes la ruta de la consulta se corrompía y nunca llegaba' } },
      { type: 'new',    text: { en: 'KPIs and charts per resource type — the Overview now groups metrics by resource (and by Kubernetes kind: Deployments, Pods, Services, Ingresses...) from a single multicloud catalog, ready for EC2, S3 and future providers', es: 'KPI y gráficos por tipo de recurso — el Overview ahora agrupa métricas por recurso (y por kind de Kubernetes: Deployments, Pods, Services, Ingresses...) desde un catálogo único multicloud, listo para EC2, S3 y futuros proveedores' } },
      { type: 'new',    text: { en: 'Node and Ingress metrics — cluster nodes report CPU, memory and hosted Pods via Prometheus, Ingresses their routing inventory, and each section shows its own resource count without repeating other counters', es: 'Métricas de nodos e Ingress — los nodos del clúster reportan CPU, memoria y Pods alojados vía Prometheus, los Ingress su inventario de ruteo, y cada sección muestra su cantidad de recursos sin repetir contadores ajenos' } },
      { type: 'new',    text: { en: 'Log volume per workload — Deployments and Pods report how much log they write to disk, and types without a collector (Secrets, ConfigMaps) are summed up in one compact line instead of a section each', es: 'Volumen de logs por workload — Deployments y Pods reportan cuánto log escriben en disco, y los tipos sin colector (Secrets, ConfigMaps) se resumen en una línea compacta en vez de ocupar una sección cada uno' } },
      { type: 'fix',    text: { en: 'Collection confirmation with Kubernetes — it now lists which Kubernetes resources will be read and makes clear it does not use the AWS budget; also, Secrets and ConfigMaps no longer cause one error per resource on every cycle', es: 'Confirmación de recolección con Kubernetes — ahora detalla qué recursos Kubernetes se van a leer y aclara que no consume el presupuesto AWS; además los Secrets y ConfigMaps ya no generan un error por recurso en cada ciclo' } },
      { type: 'new',    text: { en: 'Relationships view — review and accept or reject the relationships discovered from Observability (AWS and Kubernetes), with auto-confirmation of those declared by the resource itself; "divergent" is now called "to review"', es: 'Vista de Relaciones — revisa y acepta o rechaza las relaciones descubiertas desde Observability (AWS y Kubernetes), con auto-confirmación de las declaradas por el propio recurso; "divergentes" pasó a llamarse "por revisar"' } },
      { type: 'fix',    text: { en: 'Relationships lost on import — relationships with resources already in the project were silently dropped (which is why Deployments and Pods did not link on the canvas); also, cluster nodes are now identified by their real EC2 instance', es: 'Relaciones perdidas al importar — las relaciones con recursos ya presentes en el proyecto se descartaban en silencio (por eso Deployments y Pods no se enlazaban en el canvas); además los nodos del clúster ahora se identifican con su instancia EC2 real' } },
      { type: 'new',    text: { en: 'EC2 and S3 metrics via CloudWatch — instance CPU, network and status checks, and bucket storage and objects; also, EKS, RDS, API Gateway, CloudFront, Auto Scaling and ElastiCache now reach the Observability inventory', es: 'Métricas de EC2 y S3 vía CloudWatch — CPU, red y chequeos de estado de las instancias, y almacenamiento y objetos de los buckets; además EKS, RDS, API Gateway, CloudFront, Auto Scaling y ElastiCache ya llegan al inventario de Observability' } },
    ],
  },
  {
    version: '1.11.3',
    date: { en: 'August 2026', es: 'Agosto 2026' },
    items: [
      { type: 'fix',    text: { en: 'macOS Intel — fixed the ARM64 SQLite native module included by mistake, which kept the backend from starting after installing the app', es: 'macOS Intel — corregido el módulo nativo SQLite ARM64 incluido por error, que impedía iniciar el backend después de instalar la aplicación' } },
      { type: 'better', text: { en: 'macOS release — isolated, sequential x64 and ARM64 builds, with an architecture check inside the final ZIP files', es: 'Release macOS — builds x64 y ARM64 aislados y secuenciales, con validación de arquitectura dentro de los ZIP finales' } },
      { type: 'better', text: { en: 'macOS updates — combined manifest to keep both the x64 and ARM64 artifacts', es: 'Actualizaciones macOS — manifiesto combinado para conservar los artefactos x64 y ARM64' } },
    ],
  },
  {
    version: '1.11.2',
    date: { en: 'August 2026', es: 'Agosto 2026' },
    items: [
      { type: 'new',    text: { en: 'Multicloud APM — applications isolated per provider for AWS, GCP and Vercel, plus a provider-free General scope for Kubernetes', es: 'APM multicloud — aplicaciones aisladas por proveedor para AWS, GCP y Vercel, más un ámbito General sin proveedor para Kubernetes' } },
      { type: 'new',    text: { en: 'Smart topology — explainable local assessment with a score, coverage, isolated resources and a split between generic relationships and operational dependencies', es: 'Topología inteligente — evaluación local explicable con puntuación, cobertura, recursos aislados y separación entre relaciones genéricas y dependencias operativas' } },
      { type: 'new',    text: { en: 'AWS Step Functions — on-demand ASL analysis for Lambda, sub-workflows, SQS, ECS and S3, with external references that can be added after explicit confirmation', es: 'AWS Step Functions — análisis ASL bajo demanda para Lambda, subflujos, SQS, ECS y S3, con referencias externas agregables y confirmación explícita' } },
      { type: 'new',    text: { en: 'Process traces — search by request/correlation ID, execution ARN or Step Function ARN, with a picker of recent executions', es: 'Trazas de procesos — búsqueda por request/correlation ID, ARN de ejecución o ARN de Step Function, con selector de ejecuciones recientes' } },
      { type: 'new',    text: { en: 'Requests and responses — optional inspection per execution and per step with sensitive fields hidden, bounded structures and no stored payloads', es: 'Requests y responses — inspección opcional por ejecución y por paso con campos sensibles ocultos, estructuras acotadas y sin persistencia de payloads' } },
      { type: 'better', text: { en: 'Credentials — bilingual guide for AWS, GCP, Vercel and Kubernetes, fixed profile persistence and clearer support for local configuration', es: 'Credenciales — guía bilingüe para AWS, GCP, Vercel y Kubernetes, persistencia corregida de perfiles y soporte más claro para configuración local' } },
      { type: 'fix',    text: { en: 'Vercel — current API endpoints and versions, support for new and old Cron responses, and more precise upstream errors', es: 'Vercel — endpoints y versiones API actuales, compatibilidad con respuestas Cron nuevas y antiguas, y errores upstream más precisos' } },
      { type: 'fix',    text: { en: 'APM — SQLite migration with explicit columns, deferred GCP loading, strict per-profile/provider scoping and the AWS budget applied to analysis and traces', es: 'APM — migración SQLite por columnas explícitas, carga GCP diferida, scoping estricto por perfil/proveedor y presupuesto AWS aplicado a análisis y trazas' } },
    ],
  },
  {
    version: '1.11.0',
    date: { en: 'August 2026', es: 'Agosto 2026' },
    items: [
      { type: 'new',    text: { en: 'Local APM — per-profile application workspace with explicitly confirmed Lambda, Kubernetes, SQS, EventBridge, Step Functions and ECS resources', es: 'APM local — espacio de aplicaciones por perfil con recursos Lambda, Kubernetes, SQS, EventBridge, Step Functions y ECS confirmados explícitamente' } },
      { type: 'new',    text: { en: 'AWS discovery — read-only CloudFormation and ECS preview to import topology without automatic associations or dependency inference', es: 'Discovery AWS — preview read-only de CloudFormation y ECS para importar topología sin asociaciones automáticas ni inferencia de dependencias' } },
      { type: 'new',    text: { en: 'EKS observability — Container Insights dashboard with metrics grouped by namespace, workload, pod or node', es: 'Observabilidad EKS — dashboard de Container Insights con métricas agrupadas por namespace, workload, pod o nodo' } },
      { type: 'better', text: { en: 'Cost and privacy — polling off by default, a maximum budget of 100,000 AWS reads per month and local storage without logs, payloads or credentials', es: 'Coste y privacidad — polling desactivado por defecto, presupuesto máximo de 100.000 lecturas AWS al mes y almacenamiento local sin logs, payloads ni credenciales' } },
      { type: 'new',    text: { en: 'Private SQLite — 30-minute UTC aggregates, local thresholds, cursors, automatic retention and safe shutdown inside KUA\'s data directory', es: 'SQLite privado — agregados UTC de 30 minutos, umbrales locales, cursores, retención automática y cierre seguro dentro del directorio de datos de KUA' } },
      { type: 'better', text: { en: 'Auto-refresh — silent update every 5 seconds for Kubernetes, AWS, GCP and Vercel with a stale-while-revalidate cache and a pause while the window is hidden', es: 'Auto-refresh — actualización silenciosa cada 5 segundos para Kubernetes, AWS, GCP y Vercel con caché stale-while-revalidate y pausa al ocultar la ventana' } },
      { type: 'better', text: { en: 'Terminal logs — live follow, block navigation, pod selection for workloads and memory capped at the 5,000 most recent lines', es: 'Terminal Logs — seguimiento en vivo, navegación por bloques, selección de pod para workloads y memoria acotada a las 5.000 líneas más recientes' } },
      { type: 'fix',    text: { en: 'Kubernetes — support for the client\'s current signatures, editable YAML without managed fields and protection against stale resource responses', es: 'Kubernetes — compatibilidad con firmas actuales del cliente, YAML editable sin campos administrados y protección frente a respuestas de recursos obsoletas' } },
      { type: 'fix',    text: { en: 'Runtime — idempotent repair of the SQLite native ABI, Electron packaging and a strict Vite port for a stable dev:full', es: 'Runtime — reparación idempotente del ABI nativo de SQLite, empaquetado Electron y puerto Vite estricto para un dev:full estable' } },
    ],
  },
  {
    version: '1.10.5',
    date: { en: 'July 2026', es: 'Julio 2026' },
    items: [
      { type: 'fix',    text: { en: 'Development — separate ports for the stable backend (7190), the dev/Electron backend (7192) and the Vite frontend (7193)', es: 'Desarrollo — puertos separados para backend estable (7190), backend dev/Electron (7192) y frontend Vite (7193)' } },
      { type: 'fix',    text: { en: 'Release — workaround for optional native modules to avoid electron-rebuild failures in multiplatform builds', es: 'Release — workaround de módulos nativos opcionales para evitar fallos de electron-rebuild en builds multiplataforma' } },
    ],
  },
  {
    version: '1.10.4',
    date: { en: 'June 2026', es: 'Junio 2026' },
    items: [
      { type: 'fix',    text: { en: 'Vercel Marketplace — full support for the Marketplace OAuth flow with configurationId, teamId and next', es: 'Vercel Marketplace — soporte completo del flujo OAuth de Marketplace con configurationId, teamId y next' } },
      { type: 'fix',    text: { en: 'Vercel OAuth — the callback no longer fails with "Missing OAuth parameters" in the Marketplace flow (no state)', es: 'Vercel OAuth — callback ya no falla con "Missing OAuth parameters" en flujo de Marketplace (sin state)' } },
      { type: 'new',    text: { en: 'Vercel Marketplace — after authorization, Vercel\'s next URL opens to mark the integration as installed', es: 'Vercel Marketplace — al completar la autorización se abre la URL next de Vercel para marcar la integración como instalada' } },
      { type: 'better', text: { en: 'Vercel Marketplace — the Marketplace VERCEL_CONFIGURATION_ID and VERCEL_TEAM_ID are saved in the credential profile', es: 'Vercel Marketplace — VERCEL_CONFIGURATION_ID y VERCEL_TEAM_ID del Marketplace se persisten en el perfil de credenciales' } },
    ],
  },
  {
    version: '1.10.3',
    date: { en: 'June 2026', es: 'Junio 2026' },
    items: [
      { type: 'new',    text: { en: 'Vercel OAuth — HTTPS redirect to the public callback page to finish authorization without relying on kua://', es: 'Vercel OAuth — redirect HTTPS a la página de callback pública para completar la autorización sin depender de kua://' } },
      { type: 'new',    text: { en: 'Vercel OAuth — callback page that forwards the code/state to the desktop app automatically', es: 'Vercel OAuth — página de callback con auto-forward del code/state hacia la app de escritorio' } },
      { type: 'better', text: { en: 'Vercel OAuth — explicit runtime support for VERCEL_OAUTH_REDIRECT_URI to align local and packaged builds', es: 'Vercel OAuth — soporte explícito de VERCEL_OAUTH_REDIRECT_URI en runtime para alinear builds locales y empaquetados' } },
    ],
  },
  {
    version: '1.10.2',
    date: { en: 'June 2026', es: 'Junio 2026' },
    items: [
      { type: 'new',    text: { en: 'AWS — full support for temporary credentials with AWS_SESSION_TOKEN in saved profiles and resolution of STS sessions', es: 'AWS — soporte completo de credenciales temporales con AWS_SESSION_TOKEN en perfiles guardados y resolución de sesiones STS' } },
      { type: 'new',    text: { en: 'AWS IAM Identity Center (SSO) — browser-based flow with device authorization, account/role listing and automatic capture of temporary credentials', es: 'AWS IAM Identity Center (SSO) — flujo browser-based con autorización por dispositivo, listado de cuentas/roles y captura automática de credenciales temporales' } },
      { type: 'new',    text: { en: 'AWS SSO — expiry tracking and session renewal with structured metadata saved in meta.__sso', es: 'AWS SSO — seguimiento de expiración y renovación de sesión con metadata estructurada persistida en meta.__sso' } },
      { type: 'fix',    text: { en: 'AWS security — local profile endpoints and SSO bootstrap restricted to localhost to avoid remote exposure of local metadata', es: 'Seguridad AWS — endpoints de perfiles locales y bootstrap SSO restringidos a localhost para evitar exposición remota de metadata local' } },
      { type: 'fix',    text: { en: 'Env Manager — updated meta sanitizing to keep __sso (startUrl, ssoRegion, accountId, roleName, expiresAt) without breaking tags on generic keys', es: 'Env Manager — sanitización de meta actualizada para preservar __sso (startUrl, ssoRegion, accountId, roleName, expiresAt) sin romper tags en claves genéricas' } },
      { type: 'fix',    text: { en: 'SSO frontend — window.open hardened with noopener,noreferrer to mitigate reverse tabnabbing', es: 'Frontend SSO — window.open endurecido con noopener,noreferrer para mitigar reverse-tabnabbing' } },
      { type: 'fix',    text: { en: 'Build output — normalized line endings in public/index.html to remove leftover CR characters', es: 'Build output — normalización de line endings en public/index.html para eliminar caracteres CR residuales' } },
      { type: 'fix',    text: { en: 'AWS Step Functions — fixed the UI freezing when rendering diagrams with cycles (cycle guard in the BFS level assignment)', es: 'AWS Step Functions — corregido congelamiento de la UI al renderizar diagramas con ciclos (guard de ciclo en asignación BFS de niveles)' } },
      { type: 'fix',    text: { en: 'AWS Athena — added an S3 output override to run queries when the workgroup has no output location configured', es: 'AWS Athena — añadido override de output S3 para ejecutar queries cuando el workgroup no tiene output location configurado' } },
    ],
  },
  {
    version: '1.10.0',
    date: { en: 'June 2026', es: 'Junio 2026' },
    items: [
      { type: 'new',    text: { en: 'GCP Cloud Run — redesigned master-detail panel: service list on the left, Overview (config/image/scaling), Revisions (with traffic %), Variables and Logs tabs on the right', es: 'GCP Cloud Run — rediseño con panel master-detail: lista de servicios a la izquierda, tabs Overview (config/imagen/escalado), Revisions (con % de tráfico), Variables y Logs a la derecha' } },
      { type: 'new',    text: { en: 'GCP Compute VMs — detail panel with Overview (tags, labels, protection), Disks, Network (interfaces/IPs) and Logs from Cloud Logging tabs', es: 'GCP Compute VMs — panel de detalle con tabs Overview (tags, labels, protection), Discos, Red (interfaces/IPs) y Logs desde Cloud Logging' } },
      { type: 'new',    text: { en: 'GCP Cloud SQL — detail panel with Overview (backup/availability), Config (storage/flags), Connection (IPs/connection name) and Logs tabs', es: 'GCP Cloud SQL — panel de detalle con tabs Overview (backup/disponibilidad), Config (storage/flags), Connection (IPs/connection name) y Logs' } },
      { type: 'new',    text: { en: 'GCP Cloud Functions — detail panel with Overview (runtime/resources), Variables, Logs and inline Invoke tabs (replaces the floating modal)', es: 'GCP Cloud Functions — panel de detalle con tabs Overview (runtime/recursos), Variables, Logs e Invoke inline (reemplaza el modal flotante)' } },
      { type: 'new',    text: { en: 'GCP Cloud Monitoring metrics — "Metrics" tab embedded in Cloud Run, VMs, SQL and Functions with 3 line charts per service, a range picker (1h–24h) and refresh', es: 'GCP Métricas Cloud Monitoring — tab "Metrics" embebida en Cloud Run, VMs, SQL y Functions con 3 gráficas de línea por servicio, selector de rango (1h–24h) y refresh' } },
      { type: 'new',    text: { en: 'GCP Cloud Run metrics — Request Rate (req/s), Latency p99 (ms) and Instance Count via the Cloud Monitoring API', es: 'GCP Cloud Run Metrics — Request Rate (req/s), Latency p99 (ms) e Instance Count vía Cloud Monitoring API' } },
      { type: 'new',    text: { en: 'GCP Compute VM metrics — CPU Utilization (%), Network In (B/s) and Disk Read (B/s) via the Cloud Monitoring API', es: 'GCP Compute VM Metrics — CPU Utilization (%), Network In (B/s) y Disk Read (B/s) vía Cloud Monitoring API' } },
      { type: 'new',    text: { en: 'GCP Cloud SQL metrics — CPU Utilization (%), Connections and Disk Used (bytes) via the Cloud Monitoring API', es: 'GCP Cloud SQL Metrics — CPU Utilization (%), Connections y Disk Used (bytes) vía Cloud Monitoring API' } },
      { type: 'new',    text: { en: 'GCP Cloud Functions metrics — Execution Count (req/s), Duration p99 (ns) and Active Instances via the Cloud Monitoring API', es: 'GCP Cloud Functions Metrics — Execution Count (req/s), Duration p99 (ns) y Active Instances vía Cloud Monitoring API' } },
      { type: 'new',    text: { en: 'GCP Cloud Storage — Upload button in the GCS Browser: uploads several files to the current folder with a progress counter and a per-file result log', es: 'GCP Cloud Storage — botón Upload en el GCS Browser: sube múltiples archivos a la carpeta actual con contador de progreso y log de resultados por archivo' } },
      { type: 'new',    text: { en: 'GCP Cloud Storage — Delete button in the GCS Browser preview panel: deletes the selected object after confirmation', es: 'GCP Cloud Storage — botón Delete en el panel de preview del GCS Browser: elimina el objeto seleccionado con confirmación' } },
      { type: 'new',    text: { en: 'GCP Artifact Registry — redesigned master-detail panel: repository list on the left, "Packages & Tags" and "Deploy to K8s" tabs on the right', es: 'GCP Artifact Registry — rediseño con panel master-detail: lista de repos a la izquierda, tabs "Packages & Tags" y "Deploy to K8s" a la derecha' } },
      { type: 'new',    text: { en: 'GCP Artifact Registry — Deploy to K8s: pick the namespace, deployment and container in the active cluster, confirm the summary and apply the image change with one click', es: 'GCP Artifact Registry — Deploy to K8s: selecciona namespace, deployment y container del cluster activo, confirma el resumen y aplica el cambio de imagen con un clic' } },
      { type: 'new',    text: { en: 'Kubernetes — set-image endpoint: updates the image of a specific container in a Deployment via strategic merge patch (recorded in the audit log)', es: 'Kubernetes — endpoint set-image: actualiza la imagen de un container específico en un Deployment vía strategic merge patch (registrado en audit log)' } },
      { type: 'better', text: { en: 'GCP — inline logs with color by severity (ERROR=red, WARNING=yellow, INFO=green) in every detail panel', es: 'GCP — logs inline con visor de color por severidad (ERROR=rojo, WARNING=amarillo, INFO=verde) en todos los paneles de detalle' } },
      { type: 'better', text: { en: 'GCP — the VM detail now exposes the numeric instanceId needed for Cloud Monitoring Compute queries', es: 'GCP — detalle de VM ahora expone instanceId numérico necesario para queries de Cloud Monitoring Compute' } },
    ],
  },
  {
    version: '1.9.3',
    date: { en: 'June 2026', es: 'Junio 2026' },
    items: [
      { type: 'better', text: { en: 'AWS Amazon Lex — module redesigned with a split master-detail layout (like Cognito and Athena): bot list on the left, tabbed detail on the right', es: 'AWS Amazon Lex — rediseño del módulo con layout master-detail de panel dividido (igual al de Cognito y Athena): lista de bots a la izquierda, detalle con tabs a la derecha' } },
      { type: 'better', text: { en: 'AWS Amazon Lex — removed the 8 colored action buttons per row; every feature (Intents, Aliases, Slot Types, Chat, Logs, Missed, Metrics, Test Set) is now a tab in the detail panel', es: 'AWS Amazon Lex — eliminados los 8 botones de acción de colores por fila; toda la funcionalidad (Intents, Aliases, Slot Types, Chat, Logs, Missed, Metrics, Test Set) unificada en tabs del panel de detalle' } },
      { type: 'better', text: { en: 'AWS Amazon Lex — data loaded on demand per tab with a per-bot cache; Chat and Build from Aliases now go to their tab instead of opening nested modals', es: 'AWS Amazon Lex — datos cargados bajo demanda por tab con caché por bot; Chat y Build desde Aliases ahora navegan a su tab correspondiente en lugar de abrir modales anidados' } },
    ],
  },
  {
    version: '1.9.2',
    date: { en: 'June 2026', es: 'Junio 2026' },
    items: [
      { type: 'new',    text: { en: 'AWS DynamoDB — item editing in the Browse modal: the ✏️ button on each row opens a prefilled JSON editor; saving runs PutItem and refreshes the current page', es: 'AWS DynamoDB — edición de ítems en el modal Browse: botón ✏️ por fila abre editor JSON pre-llenado; al guardar ejecuta PutItem y refresca la página actual' } },
      { type: 'new',    text: { en: 'AWS DynamoDB — per-row item deletion: the 🗑 button takes the primary key from the key schema automatically and asks for confirmation before DeleteItem', es: 'AWS DynamoDB — eliminación de ítems por fila: botón 🗑 extrae la clave primaria automáticamente desde el key schema y pide confirmación antes de DeleteItem' } },
      { type: 'new',    text: { en: 'AWS DynamoDB — New Item button in the Browse toolbar: opens a JSON editor prefilled with only the key fields to create records from scratch', es: 'AWS DynamoDB — botón New Item en el toolbar del Browse: abre editor JSON pre-llenado solo con los campos de clave para crear registros desde cero' } },
      { type: 'better', text: { en: 'AWS DynamoDB — the JSON editor checks syntax in real time and blocks saving when there are parse errors', es: 'AWS DynamoDB — editor JSON valida sintaxis en tiempo real y bloquea el guardado si hay errores de parseo' } },
    ],
  },
  {
    version: '1.9.1',
    date: { en: 'May 2026', es: 'Mayo 2026' },
    items: [
      { type: 'fix',    text: { en: 'AWS Cognito — improved user search to support free text without filter parse errors on AWS', es: 'AWS Cognito — búsqueda de usuarios mejorada para soportar texto libre sin errores de parseo de filtros en AWS' } },
      { type: 'new',    text: { en: 'AWS Cognito — edit user attributes from the details modal', es: 'AWS Cognito — edición de atributos de usuario desde el modal de detalles' } },
      { type: 'new',    text: { en: 'AWS Cognito — manage a user\'s groups from the details: add and remove memberships', es: 'AWS Cognito — gestión de grupos por usuario desde detalles: asignar y remover memberships' } },
      { type: 'new',    text: { en: 'AWS Cognito — per-user MFA control in the details: turn on with a toggle, turn off with an action and change the preferred method (SMS/TOTP)', es: 'AWS Cognito — control de MFA por usuario en detalles: activar con toggle, desactivar con acción y cambiar método preferido (SMS/TOTP)' } },
      { type: 'new',    text: { en: 'AWS Cognito — create groups with a description in the Groups tab', es: 'AWS Cognito — creación de grupos con soporte de descripción en la pestaña Groups' } },
      { type: 'fix',    text: { en: 'AWS Cognito — fixed a runtime error when creating groups (createCognitoGroup is not a function) in stale hot-reload states', es: 'AWS Cognito — corregido error runtime de creación de grupos (createCognitoGroup is not a function) en estados stale de hot-reload' } },
      { type: 'fix',    text: { en: 'AWS Cognito — aligned the MFA state between the list and the details using UserMFASettingList/PreferredMfaSetting with a compatibility fallback', es: 'AWS Cognito — alineado el estado MFA entre lista y detalles usando UserMFASettingList/PreferredMfaSetting con fallback de compatibilidad' } },
    ],
  },
  {
    version: '1.9.0',
    date: { en: 'May 2026', es: 'Mayo 2026' },
    items: [
      { type: 'new',    text: { en: 'Vercel — full integration: OAuth sign-in, projects, deployments, activity, DNS records, aliases, cron jobs, webhooks, Edge Config and checks', es: 'Vercel — integración completa: autenticación OAuth, proyectos, deployments, actividad, DNS Records, Aliases, Cron Jobs, Webhooks, Edge Config y Checks' } },
      { type: 'new',    text: { en: 'AWS Step Functions — "Executions" column in the table with live counts of running (▶), failed (✗) and timed-out (⏱) executions', es: 'AWS Step Functions — columna "Executions" en la tabla con conteos en vivo de ejecuciones activas (▶), fallidas (✗) y con timeout (⏱)' } },
      { type: 'new',    text: { en: 'AWS Step Functions — "Versions" tab in the Info panel: the workflow\'s published versions with their ASL definition and a copy button per version', es: 'AWS Step Functions — pestaña "Versiones" en el panel Info: lista de versiones publicadas del workflow con definición ASL y botón de copia por versión' } },
      { type: 'better', text: { en: 'AWS Step Functions — Info modal refactored with tabs: Details, Diagram, Executions, Events and Versions', es: 'AWS Step Functions — modal Info refactorizado con pestañas: Detalles, Diagrama, Ejecuciones, Eventos y Versiones' } },
      { type: 'new',    text: { en: 'Terminal & Shell — native copy/paste support in the Electron menu and the context menu (right click)', es: 'Terminal & Shell — soporte nativo de copy/paste en menú de Electron y menú contextual (click derecho)' } },
      { type: 'new',    text: { en: 'Terminal & Shell — Copy Selected, Copy Output and Paste into Input actions, with confirmation for multi-line text', es: 'Terminal & Shell — acciones Copy Selected, Copy Output y Paste into Input con confirmación para texto multilínea' } },
      { type: 'new',    text: { en: 'Local Shell / EC2 SSH / terminal panel — dedicated copy/paste buttons and a safe paste flow', es: 'Local Shell / EC2 SSH / panel de terminal — botones dedicados de copiar/pegar y flujo seguro de pegado' } },
      { type: 'better', text: { en: 'Terminal output — fixed text selection (user-select: text) while keeping decorative elements unselectable', es: 'Terminal output — fix de selección de texto (user-select: text) preservando elementos decorativos no seleccionables' } },

    ],
  },
  {
    version: '1.8.0',
    date: { en: 'May 2026', es: 'Mayo 2026' },
    items: [
      { type: 'new',    text: { en: 'Kubernetes — multiple selection in resource tables, bulk deletion and Age sorted by real duration with a days/hours/minutes/seconds format', es: 'Kubernetes — selección múltiple en tablas de recursos, eliminación masiva y ordenamiento de Age por duración real con formato días/horas/minutos/segundos' } },
      { type: 'new',    text: { en: 'Kubernetes — bigger menu with more workload, networking, storage, config, policy, RBAC, scheduling, admission and cluster resources', es: 'Kubernetes — menú ampliado con más recursos de workloads, networking, storage, config, policy, RBAC, scheduling, admission y cluster' } },
      { type: 'new',    text: { en: 'ConfigMaps and Secrets — key/value data editor, simple mapping and a view of the related environment variables', es: 'ConfigMaps y Secrets — editor de datos en formato clave/valor, mapeo sencillo y vista de variables de entorno asociadas' } },
      { type: 'new',    text: { en: 'Workloads — edit container environment variables from the detail panel', es: 'Workloads — edición de variables de entorno para contenedores desde el panel de detalle' } },
      { type: 'new',    text: { en: 'Helm — chart search, direct install on the cluster, management of installed releases and visible install status/output', es: 'Helm — búsqueda de charts, instalación directa en el cluster, gestión de releases instalados y estado/output de instalación visible' } },
      { type: 'new',    text: { en: 'Helm — metrics-server compatibility preset with kubelet TLS and preferred address flags for local or self-signed clusters', es: 'Helm — preset de compatibilidad para metrics-server con flags de kubelet TLS y dirección preferida para clusters locales o self-signed' } },
      { type: 'new',    text: { en: 'Observability — metrics for Pods, workloads and Nodes with metrics.k8s.io and a fallback through Prometheus found in the cluster\'s Services', es: 'Observabilidad — métricas para Pods, workloads y Nodes con metrics.k8s.io y fallback vía Prometheus detectado en Services del cluster' } },
      { type: 'new',    text: { en: 'Events — viewer of events and related notifications for resources and Nodes from the detail panel', es: 'Eventos — visor de eventos y notificaciones relacionadas para recursos y Nodes desde el panel de detalle' } },
      { type: 'new',    text: { en: 'Kubeconfig — import from pasted YAML, from a local file through Electron, and manual registration of existing paths', es: 'Kubeconfig — importación desde YAML pegado, archivo local mediante Electron y registro manual de rutas existentes' } },
      { type: 'fix',    text: { en: 'Port forwarding — more stable tunnels for Services and Pods with target pod resolution, persistent state and reconnection', es: 'Port Forwarding — túneles más estables para Services y Pods con resolución de pod objetivo, estado persistente y reconexión' } },
    ],
  },
  {
    version: '1.7.0',
    date: { en: 'May 2026', es: 'Mayo 2026' },
    items: [
      { type: 'new',    text: { en: 'Kubernetes — auto-refresh per active view: Kubernetes, AWS, GCP and Helm update their resources without losing your working context', es: 'Kubernetes — auto-refresh por vista activa: Kubernetes, AWS, GCP y Helm actualizan sus recursos sin perder el contexto de trabajo' } },
      { type: 'new',    text: { en: 'Kubernetes — side detail panel per resource with a specialized summary, structured YAML, sections per type and adjustable width', es: 'Kubernetes — panel lateral de detalle por recurso con resumen especializado, YAML estructurado, secciones por tipo y ancho ajustable' } },
      { type: 'new',    text: { en: 'Kubernetes — visual Pod metrics using metrics.k8s.io and Prometheus detection, with a shortcut to Helm when no observability is installed', es: 'Kubernetes — métricas visuales para Pods usando metrics.k8s.io y detección de Prometheus, con acceso directo a Helm cuando no hay observabilidad instalada' } },
      { type: 'new',    text: { en: 'Kubernetes logs — real-time streaming for Pods, Deployments, StatefulSets and DaemonSets with pod resolution by selector', es: 'Kubernetes Logs — streaming en tiempo real para Pods, Deployments, StatefulSets y DaemonSets con resolución de pods por selector' } },
      { type: 'new',    text: { en: 'Terminal logs — search, filters by serialized date, log download and a count of filtered lines', es: 'Terminal Logs — buscador, filtros por fecha serializada, descarga de logs y conteo de líneas filtradas' } },
      { type: 'better', text: { en: 'Terminal logs — cleanup of ANSI/VT sequences and a fragment buffer to serialize logs from frameworks like NestJS correctly', es: 'Terminal Logs — limpieza de secuencias ANSI/VT y buffer de fragmentos para serializar correctamente logs de frameworks como NestJS' } },
      { type: 'new',    text: { en: 'YAML editor — search with confirmation, Save button, validation/lint, line/column/total line status, section path and autocomplete with Ctrl+Space', es: 'YAML Editor — búsqueda por confirmación, botón Guardar, validación/lint, estado de línea/columna/total de líneas, ruta de sección y autocompletado con Ctrl+Space' } },
      { type: 'new',    text: { en: 'AWS EC2 — persistent SSH/RDP sessions in tabs: hiding a console no longer drops the connection, and it can be reopened from the session tray', es: 'AWS EC2 — sesiones SSH/RDP persistentes en tabs: ocultar una consola ya no corta la conexión y se puede reabrir desde la bandeja de sesiones' } },
      { type: 'fix',    text: { en: 'AWS — fixed the vue/no-v-for-template-key lint warning in the Athena view', es: 'AWS — resuelta advertencia de lint vue/no-v-for-template-key en la vista Athena' } },
    ],
  },
  {
    version: '1.6.2',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'new',    text: { en: 'AWS EC2 Info — ⧉ copy buttons on key fields: Instance ID, AMI, public/private IP, public/private DNS, key pair and IAM profile', es: 'AWS EC2 Info — botones de copia ⧉ en campos clave: Instance ID, AMI, IP Pública/Privada, DNS Público/Privado, Key Pair y Perfil IAM' } },
      { type: 'new',    text: { en: 'AWS Lambda Info — ⧉ copy buttons on key fields: ARN, SHA256, VPC ID, DLQ ARN and KMS key ARN', es: 'AWS Lambda Info — botones de copia ⧉ en campos clave: ARN, SHA256, VPC ID, DLQ ARN y KMS Key ARN' } },
      { type: 'better', text: { en: 'UX — the copy button shows on hover and confirms with ✓ for 1.5 s; no external dependencies (native Clipboard API)', es: 'UX — el botón de copia aparece al hacer hover y confirma visualmente con ✓ durante 1.5 s; sin dependencias externas (Clipboard API nativa)' } },
    ],
  },
  {
    version: '1.6.1',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'new',    text: { en: 'AWS RDS — new per-instance panel with Info, Configuration, Connection and Reset password actions', es: 'AWS RDS — nuevo panel por instancia con acciones Info, Configuración, Conexión y Restablecer contraseña' } },
      { type: 'new',    text: { en: 'AWS RDS — detail modal redesigned with AWS console-style tabs: Connectivity and security, Monitoring and logs, Configuration, Maintenance and backups, Migration and replicas, and Tags', es: 'AWS RDS — modal de detalle rediseñado con pestañas estilo consola AWS: Conectividad y seguridad, Supervisión y registros, Configuración, Mantenimiento y copias de seguridad, Migración y réplicas, y Etiquetas' } },
      { type: 'better', text: { en: 'AWS RDS — full Spanish translation of the texts, buttons and messages in the Info, Connection and Reset password modals', es: 'AWS RDS — traducción completa al español de textos, botones y mensajes de los modales de Info, Conexión y Restablecimiento de contraseña' } },
      { type: 'better', text: { en: 'AWS Database — unified navigation and view to work under RDS, removing the leftover DocumentDB section from the interface', es: 'AWS Database — unificación de navegación y vista para trabajar bajo RDS, eliminando la sección residual de DocumentDB en la interfaz' } },
      { type: 'better', text: { en: 'Documentation — Spanish guide to minimum IAM permissions extended with the actions RDS needs', es: 'Documentación — guía de permisos mínimos IAM en español ampliada con acciones requeridas para RDS' } },
      { type: 'fix',    text: { en: 'HelpModal — fixed badly encoded characters (mojibake) in the component\'s titles and comments', es: 'HelpModal — corregidos caracteres con encoding incorrecto (mojibake) en títulos y comentarios del componente' } },
      { type: 'fix',    text: { en: 'Helm — contexts named with an ARN (EKS) now resolve correctly; the full KUBECONFIG is passed when calling the helm CLI', es: 'Helm — contextos con nombre ARN (EKS) ya se resuelven correctamente; se inyecta KUBECONFIG completo al invocar el CLI de helm' } },
    ],
  },
  {
    version: '1.6.0',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'new',    text: { en: 'AWS Lambda — new Logs tab with a live CloudWatch viewer, a time range picker (15 min–24 h) and an option to create the log group with configurable retention if it does not exist', es: 'AWS Lambda — nuevo tab Logs con visor CloudWatch en vivo, selector de rango de tiempo (15 min–24 h) y opción de crear Log Group con retención configurable si no existe' } },
      { type: 'new',    text: { en: 'AWS Lambda — Tags moved to the grid in the Basic tab (6 tabs in total: Basic, Configuration, Logs, Monitoring, Aliases, Code)', es: 'AWS Lambda — Tags movido a la grid del tab Básico (6 tabs en total: Básico, Configuración, Logs, Monitoreo, Aliases, Código)' } },
      { type: 'new',    text: { en: 'AWS ECR Deploy to K8s — option to create a Service (ClusterIP / NodePort / LoadBalancer) along with the Deployment', es: 'AWS ECR Deploy to K8s — opción de crear Service (ClusterIP / NodePort / LoadBalancer) junto al Deployment' } },
      { type: 'fix',    text: { en: 'AWS ECR Deploy to K8s — fixed the indentation of the generated YAML that caused the "did not find expected - indicator" error', es: 'AWS ECR Deploy to K8s — corregida indentación del YAML generado que causaba error "did not find expected - indicator"' } },
      { type: 'fix',    text: { en: 'AWS ECR Deploy to K8s — added --validate=false to kubectl apply to avoid API server connection failures during schema validation', es: 'AWS ECR Deploy to K8s — añadido --validate=false a kubectl apply para evitar fallos de conexión al API server durante la validación de esquema' } },
      { type: 'fix',    text: { en: 'AWS Athena — fixed the "sortedRows is not a function" error when loading the tables view', es: 'AWS Athena — corregido error "sortedRows is not a function" al cargar la vista de tablas' } },
      { type: 'fix',    text: { en: 'AWS Lex and Athena — maxResults set to 50 (the API limit) to avoid a constraint error', es: 'AWS Lex y Athena — maxResults ajustado a 50 (límite del API) para evitar error de constraint' } },
    ],
  },
  {
    version: '1.5.0',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'new',    text: { en: 'AWS DynamoDB — Info modal with billing mode, throughput, GSIs/LSIs, stream status and ARN; + Create Table button with partition key, sort key, billing mode and RCU/WCU', es: 'AWS DynamoDB — modal Info con billing mode, throughput, GSIs/LSIs, stream status y ARN; botón + Create Table con clave de partición, sort key, modo de facturación y RCU/WCU' } },
      { type: 'new',    text: { en: 'AWS Glue — Info panel with job type, worker configuration, script location, IAM role, connections and arguments', es: 'AWS Glue — panel Info con tipo de job, configuración de workers, script location, rol IAM, conexiones y argumentos' } },
      { type: 'new',    text: { en: 'AWS Athena — full redesign with 3 sub-tabs: Workgroups, Data Sources (catalog→database→tables tree) and a Query Editor with a split panel, history and CSV export', es: 'AWS Athena — rediseño completo con 3 sub-pestañas: Workgroups, Data Sources (árbol catálogo→BD→tablas) y Query Editor con panel dividido, historial y exportación CSV' } },
      { type: 'new',    text: { en: 'AWS Lex — viewer of Intents, Slots and Slot Types in tabs inside the bot detail', es: 'AWS Lex — visor de Intents, Slots y Slot Types en pestañas dentro del detalle del bot' } },
      { type: 'new',    text: { en: 'AWS Step Functions — run state machines with a custom payload; executions viewer with status and output', es: 'AWS Step Functions — ejecución de state machines con payload personalizado; visor de ejecuciones con estado y salida' } },
    ],
  },
  {
    version: '1.4.3',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'fix',    text: { en: 'Windows: the app icon no longer shows as the generic Electron one — the App User Model ID (dev.kua.kuadashboard) is registered for the taskbar, alt+tab and notifications', es: 'Windows: el icono de la app ya no aparece como Electron genérico — se registra el App User Model ID (dev.kua.kuadashboard) para el taskbar, alt+tab y notificaciones' } },
      { type: 'better', text: { en: 'Package description updated to reflect multi-cloud support (Kubernetes, AWS and GCP)', es: 'Descripción del paquete actualizada para reflejar el soporte multi-cloud (Kubernetes, AWS y GCP)' } },
    ],
  },
  {
    version: '1.4.2',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'new',    text: { en: 'AWS Lambda — detail panel with 5 tabs: Overview, Code Viewer, Environment variables, Triggers and real-time Logs', es: 'AWS Lambda — panel de detalle con 5 pestañas: Overview, Code Viewer, Variables de entorno, Triggers y Logs en tiempo real' } },
      { type: 'new',    text: { en: 'AWS EC2 — detail panel with 5 tabs: Overview, Monitoring, Security Groups, Volumes and Console Output', es: 'AWS EC2 — panel de detalle con 5 pestañas: Overview, Monitoring, Security Groups, Volumes y Console Output' } },
      { type: 'new',    text: { en: 'AWS EC2 — SSH sign-in with a password as well as PEM; built-in PEM file picker', es: 'AWS EC2 — autenticación SSH con contraseña además de PEM; selector de archivo PEM integrado' } },
      { type: 'new',    text: { en: 'AWS EC2 — OS-aware SSH/RDP buttons; built-in RDP canvas', es: 'AWS EC2 — botones SSH/RDP conscientes del SO; canvas RDP integrado' } },
    ],
  },
  {
    version: '1.4.1',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'fix',    text: { en: 'Auto-updater: try-catch around quitAndInstall with a fallback to app.quit() to avoid hangs while installing the update', es: 'Auto-updater: try-catch en quitAndInstall con fallback a app.quit() para evitar cuelgues al instalar la actualización' } },
      { type: 'fix',    text: { en: 'UpdateNotice: shows an error state with a "Download manually" button that opens the releases page', es: 'UpdateNotice: muestra estado de error con botón "Descargar manualmente" que abre la página de releases' } },
    ],
  },
  {
    version: '1.4.0',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'new',    text: { en: 'GCP Cloud Run Jobs — list and run jobs and see their execution history', es: 'GCP Cloud Run Jobs — lista, ejecuta jobs y consulta historial de ejecuciones' } },
      { type: 'new',    text: { en: 'GCP Pub/Sub Subscriptions — list subscriptions with type (push/pull), topic, filter and ack deadline', es: 'GCP Pub/Sub Subscriptions — lista suscripciones con tipo (push/pull), topic, filtro y ack deadline' } },
      { type: 'new',    text: { en: 'GCP VPC Networks — networks and subnets with CIDR, gateway, Private Google Access and Flow Logs', es: 'GCP VPC Networks — redes y subnets con CIDR, gateway, Private Google Access y Flow Logs' } },
      { type: 'new',    text: { en: 'GCP Cloud Monitoring — alert policies and uptime checks with enabled/disabled status', es: 'GCP Cloud Monitoring — alert policies y uptime checks con estado habilitado/deshabilitado' } },
      { type: 'new',    text: { en: 'GCP Cloud Logging — interactive query panel with a filter, an hour range and real-time results', es: 'GCP Cloud Logging — panel de query interactivo con filtro, rango de horas y resultados en tiempo real' } },
      { type: 'new',    text: { en: 'GCP Cloud KMS — key rings and crypto keys per location with purpose, algorithm and rotation', es: 'GCP Cloud KMS — key rings y crypto keys por ubicación con propósito, algoritmo y rotación' } },
      { type: 'better', text: { en: 'Pagination (Load more) in Cloud Build, IAM Service Accounts and Cloud Tasks', es: 'Paginación (Load more) en Cloud Build, IAM Service Accounts y Cloud Tasks' } },
      { type: 'better', text: { en: 'New Observability section in the GCP sidebar', es: 'Nueva sección Observabilidad en el sidebar GCP' } },
    ],
  },
  {
    version: '1.3.3',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'fix',  text: { en: 'macOS: credentials stored in the native Keychain using @napi-rs/keyring — removes the "KeytarStore requires keytar" error without rebuilding native modules', es: 'macOS: credenciales almacenadas en el Keychain nativo usando @napi-rs/keyring — elimina el error "KeytarStore requires keytar" sin necesidad de recompilar módulos nativos' } },
      { type: 'fix',  text: { en: 'macOS: the auto-updater builds a .zip file besides the .dmg, fixing the "zip file not provided" error when updating', es: 'macOS: el auto-updater genera archivo .zip además del .dmg, resolviendo el error "zip file not provided" al actualizar' } },
    ],
  },
  {
    version: '1.3.2',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'fix', text: { en: 'macOS: the auto-updater now builds a .zip file besides the .dmg, fixing the "zip file not provided" error when updating the app', es: 'macOS: el auto-updater ahora genera un archivo .zip además del .dmg, resolviendo el error "zip file not provided" al intentar actualizar la app' } },
    ],
  },
  {
    version: '1.3.1',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'fix', text: { en: 'macOS: the auto-updater now builds a .zip file besides the .dmg, fixing the "zip file not provided" error when updating the app', es: 'macOS: el auto-updater ahora genera un archivo .zip además del .dmg, resolviendo el error "zip file not provided" al intentar actualizar la app' } },
    ],
  },
  {
    version: '1.3.0',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'new',    text: { en: 'GCP phase 3: Cloud Spanner (instances, databases, SQL queries), Memorystore Redis, Cloud Tasks, Cloud Scheduler, Cloud Build and IAM Service Accounts', es: 'GCP Fase 3: Cloud Spanner (instancias, bases de datos, query SQL), Memorystore Redis, Cloud Tasks, Cloud Scheduler, Cloud Build y IAM Service Accounts' } },
      { type: 'new',    text: { en: 'Bilingual interface (EN/ES) — full i18n system with more than 150 keys and reactive switching without reloading', es: 'Interfaz bilingüe (EN/ES) — sistema i18n completo con más de 150 claves y cambio reactivo sin recargar' } },
      { type: 'new',    text: { en: 'Quick-access buttons in the header: language (🇪🇸/🇺🇸) and theme (☀/🌙)', es: 'Botones de acceso rápido en el header: cambio de idioma (🇪🇸/🇺🇸) y tema (☀/🌙)' } },
      { type: 'new',    text: { en: 'Helm view — Helm release explorer under Tools', es: 'Vista Helm — explorador de releases Helm bajo Herramientas' } },
      { type: 'new',    text: { en: 'Application menu with About, DevTools and Check for Updates', es: 'Menú de aplicación con About, DevTools y Check for Updates' } },
      { type: 'fix',    text: { en: 'WebSocket: removed the hard-coded ws://localhost:7190 URL that broke streams on setups with a non-default port', es: 'WebSocket: eliminada URL hardcoded ws://localhost:7190 que rompía streams en setups con puerto no predeterminado' } },
      { type: 'fix',    text: { en: 'Terminal minimize: the panel now collapses correctly to 34px (header only)', es: 'Terminal minimize: el panel ahora colapsa correctamente a 34px (solo cabecera)' } },
      { type: 'fix',    text: { en: 'Auto-updater: state moved to a global store — the "Restart and update" button no longer disappears when the modal closes', es: 'Auto-updater: estado movido a store global — el botón "Reiniciar y actualizar" ya no desaparece al cerrar el modal' } },
      { type: 'better', text: { en: 'Full bilingual VitePress documentation — 17 EN + ES pages covering the guide, features and architecture', es: 'Documentación bilingüe VitePress completa — 17 páginas EN + ES cubriendo guía, features y arquitectura' } },
    ],
  },
  {
    version: '1.2.0',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'new',    text: { en: 'GCP phases 1-2: Secret Manager, Cloud Functions, GCS Browser, Artifact Registry, BigQuery, Cloud Workflows, Cloud DNS, Firestore', es: 'GCP Fase 1-2: Secret Manager, Cloud Functions, GCS Browser, Artifact Registry, BigQuery, Cloud Workflows, Cloud DNS, Firestore' } },
      { type: 'new',    text: { en: 'Port forwarding that persists across sessions', es: 'Port forwarding persistente entre sesiones' } },
      { type: 'new',    text: { en: 'Full AWS support: 19 services including API Gateway, CloudFront, Route 53, DynamoDB, DocumentDB, Glue, Athena, Cognito and more', es: 'Soporte AWS completo: 19 servicios incluyendo API Gateway, CloudFront, Route 53, DynamoDB, DocumentDB, Glue, Athena, Cognito y más' } },
      { type: 'better', text: { en: 'Terminal panel with multiple tabs, line highlighting and resizing', es: 'Panel de terminal con múltiples pestañas, highlight de líneas y resize' } },
    ],
  },
  {
    version: '1.1.3',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'fix',    text: { en: 'macOS — auto-updater fix for the ZIP target (required by electron-updater)', es: 'macOS — fix de auto-updater para target ZIP (requerido por electron-updater)' } },
    ],
  },
  {
    version: '1.1.2',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'fix',  text: { en: 'macOS: Electron inherits the login shell PATH when launched from the Dock, fixing missing kubectl, aws, gcloud and helm installed with Homebrew', es: 'macOS: Electron hereda el PATH del login shell al arrancar desde el Dock, resolviendo la falta de kubectl, aws, gcloud y helm instalados con Homebrew' } },
      { type: 'new',  text: { en: 'Update available/ready notice inside the Help modal', es: 'Aviso de actualización disponible/lista dentro del modal de Ayuda' } },
    ],
  },
  {
    version: '1.1.1',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'new',    text: { en: 'AWS and GCP credentials configurable from the global header', es: 'Credenciales AWS y GCP configurables desde el header global' } },
      { type: 'new',    text: { en: 'Local Shell button always visible in the header', es: 'Botón de Local Shell siempre visible en el header' } },
      { type: 'new',    text: { en: 'Env Manager button in the header, reachable from any provider', es: 'Botón de Env Manager en el header, accesible desde cualquier proveedor' } },
      { type: 'new',    text: { en: 'Help modal with About, Releases and Feedback/Issues', es: 'Modal de Ayuda con Acerca de, Releases y Feedback/Issues' } },
      { type: 'better', text: { en: 'Uniform SVG icons across the interface (12px)', es: 'Iconos SVG uniformes en toda la interfaz (12px)' } },
      { type: 'better', text: { en: 'Refresh button with an icon in the AWS and GCP views', es: 'Botón Refresh en las vistas AWS y GCP con icono' } },
    ],
  },
  {
    version: '1.1.0',
    date: { en: 'April 2026', es: 'Abril 2026' },
    items: [
      { type: 'new',    text: { en: 'AWS and GCP credential pickers in the global header', es: 'Selectores de credencial AWS y GCP en el header global' } },
      { type: 'new',    text: { en: 'Side navigation (sidebar) for AWS and GCP', es: 'Navegación lateral (sidebar) para AWS y GCP' } },
      { type: 'new',    text: { en: 'AWS Step Functions support with diagram view', es: 'Soporte para AWS Step Functions con visualización de diagramas' } },
      { type: 'new',    text: { en: 'AWS EventBridge support — rules, logs and metrics', es: 'Soporte para AWS EventBridge — reglas, logs y métricas' } },
      { type: 'new',    text: { en: 'AWS API Gateway support — routes and integrations', es: 'Soporte para AWS API Gateway — rutas e integraciones' } },
      { type: 'new',    text: { en: 'GCP Pub/Sub — manage topics', es: 'GCP Pub/Sub — gestiona tópicos' } },
      { type: 'new',    text: { en: 'GCP Cloud Functions — invoke and monitor functions', es: 'GCP Cloud Functions — invoca y monitorea funciones' } },
      { type: 'better', text: { en: 'Direct SSH to EC2 instances from the dashboard', es: 'SSH directo a instancias EC2 desde el dashboard' } },
      { type: 'better', text: { en: 'Built-in local terminal with multiple tabs', es: 'Terminal local integrada con múltiples pestañas' } },
    ],
  },
  {
    version: '1.0.0',
    date: { en: 'January 2026', es: 'Enero 2026' },
    items: [
      { type: 'new', text: { en: 'Kubernetes dashboard to manage Pods, Deployments, Services and more', es: 'Dashboard Kubernetes con gestión de Pods, Deployments, Services y más' } },
      { type: 'new', text: { en: 'Multi-context and multi-namespace support', es: 'Soporte multi-contexto y multi-namespace' } },
      { type: 'new', text: { en: 'AWS view — EC2, ECS, EKS, Lambda, S3, ECR, VPC', es: 'Vista AWS — EC2, ECS, EKS, Lambda, S3, ECR, VPC' } },
      { type: 'new', text: { en: 'GCP view — Cloud Run, GKE, Compute VMs, Cloud SQL, Storage', es: 'Vista GCP — Cloud Run, GKE, Compute VMs, Cloud SQL, Storage' } },
      { type: 'new', text: { en: 'Env Manager to manage encrypted credential profiles', es: 'Env Manager para gestionar perfiles de credenciales cifradas' } },
      { type: 'new', text: { en: 'Visual port forwarding', es: 'Port forwarding visual' } },
      { type: 'new', text: { en: 'Log streaming and terminal exec for pods', es: 'Logs en streaming y terminal exec para pods' } },
    ],
  },
]
