const RESOURCE_PRESENTATION = Object.freeze({
  lambda: { icon: 'square-function', tone: 'compute' },
  layer: { icon: 'layers-3', tone: 'compute' },
  function: { icon: 'square-function', tone: 'compute' },
  sqs: { icon: 'messages-square', tone: 'application' },
  queue: { icon: 'messages-square', tone: 'application' },
  sns: { icon: 'megaphone', tone: 'application' },
  stepfunctions: { icon: 'workflow', tone: 'application' },
  eventbridge: { icon: 'radio-tower', tone: 'application' },
  s3: { icon: 'archive', tone: 'storage' },
  storage: { icon: 'archive', tone: 'storage' },
  dynamodb: { icon: 'database', tone: 'database' },
  database: { icon: 'database', tone: 'database' },
  iam: { icon: 'shield-user', tone: 'security-simple' },
  'iam-policy': { icon: 'file-key', tone: 'security-simple' },
  policy: { icon: 'file-text', tone: 'security-simple' },
  api: { icon: 'braces', tone: 'network' },
  'api-route': { icon: 'route', tone: 'network' },
  'api-integration': { icon: 'plug', tone: 'network' },
  ecs: { icon: 'container', tone: 'compute' },
  ec2: { icon: 'server', tone: 'compute' },
  kubernetes: { icon: 'ship-wheel', tone: 'kubernetes' },
  deployment: { icon: 'boxes', tone: 'kubernetes' },
  statefulset: { icon: 'database-zap', tone: 'kubernetes' },
  daemonset: { icon: 'rows-3', tone: 'kubernetes' },
  pod: { icon: 'container', tone: 'kubernetes' },
  service: { icon: 'network', tone: 'kubernetes-network' },
  ingress: { icon: 'route', tone: 'kubernetes-network' },
  configmap: { icon: 'file-cog', tone: 'kubernetes-config' },
  secret: { icon: 'key-round', tone: 'security-simple' },
  pvc: { icon: 'hard-drive', tone: 'storage' },
  'gcp-cloud-run': { icon: 'cloud-cog', tone: 'compute' },
  'gcp-function': { icon: 'square-function', tone: 'compute' },
  'vercel-project': { icon: 'triangle', tone: 'neutral' },
  logs: { icon: 'logs', tone: 'management' },
  secret: { icon: 'key-round', tone: 'security-simple' },
  external: { icon: 'external-link', tone: 'neutral' },
})

export function architectureResourcePresentation(resourceType) {
  return RESOURCE_PRESENTATION[resourceType] || { icon: 'box', tone: 'neutral' }
}